---
- name: Install and config reverse proxy - Nginx
  hosts: local_web-server
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Setup config Nginx
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;

              location / {
                  proxy_pass http://127.0.0.1:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }
          }

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
